baseURL = 'https://example.org/'
languageCode = "en-us"  
title = "Blogs"
theme = "pehtheme-hugo"

[pagination]
pagerSize = 6   # Set the desired number of posts per page 

[params]
	description = 'Pehtheme Hugo Lite: A minimalist Hugo theme, built with TailwindCSS, for efficient performance and minimalism.'
	mainSections = 'posts'

[author]  # Moved the author section here
	name = "Embrays Technologies"
	bio = "Technology solutions for businesses."
	avatar = "images/avatar.jpg"  # Path to the author's avatar, placed in static/images

[menu] # Menu management
	[[menu.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'About'
		pageRef = '/about'
		weight = 15
	[[menu.main]]
		name = 'Tags'
		pageRef = '/tags'
		weight = 20
	[[menu.main]]
		name = 'Taxonomy'
		pageRef = '/tags/space/'
		weight = 25

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [[module.mounts]]  # Directing the static folder to assets.
    source = 'assets'
    target = 'static'
